title: Blog César
author: César Ramírez
email: cesar.ramirez.sv@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I'm a Full Stack Developer.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
